## Name                    : Ritik Sharma
## Register Number : 23MDT0029
## Course Name       : Deep Learning-Laboratory Course
## Course Code        : MAT6007

In [2]:
import numpy as np
import random as rn
import tensorflow as tf
import pandas as pd

#### With the While loop

In [3]:
i1=float(input("Enter the first input:"))           # enter neurons as float
i2=float(input("Enter the second input: "))
actual=float(input("Enter the actual output: "))    # Enter the Actual output
rate=float(input("Enter the learning rate: "))      # Enter the Learning Rate

I=[i1,i2]                                     # make it into list
i=np.array(I)                                 #convert it into array
print(i)


l1=[rn.random() for x in range(4)]          # generate 4 random numbers for weights w1,w2,w3,w4
w1=np.array(l1)                             # converts weight into an array
w=w1.reshape(2,2)                           # convert it shape into matrix that is 2*2
print(w)


l2=[rn.random() for x in range(2)]          # generate 2 random numbers for weight for output layer
w2=np.array(l2)                             # convert it into array
print(w2)

threshold=0.01
delta=1

while abs(delta) > threshold:
    h=np.dot(i, w)                               # take dot product of the input and weights to find the hidden layers value
    ah=tf.keras.activations.tanh(h)      # Apply the activation function
    
    
    out=np.dot(w2,ah)
    o=tf.keras.activations.tanh(out)
    
    
    delta=o-actual                                           # Error Prediction value
    print("Error at the output layer is:", delta)
    
    
    # Back-Propagation Algorithm
    W2=w2-(rate*delta*ah)                                  
    print("Updated weight for output layer :", W2)
    w2=np.array(W2)
    w2=w2.reshape(1,2)
    
    temp=rate*delta*(w2.T*i)
    W1=w-temp
    print("updated weights for hidden layer:", W1)
    
    # Update weights for next iteration
    w2 = W2
    w = W1
    
    
print("Training complete.")
print("Final weights for hidden layer:", w)
print("Final weights for output layer:", w2)

Enter the first input:1.2
Enter the second input: 2.3
Enter the actual output: 1
Enter the learning rate: 0.5
[1.2 2.3]
[[0.07464127 0.62368153]
 [0.38658053 0.9164755 ]]
[0.61207329 0.05175666]
Error at the output layer is: tf.Tensor(-0.5284950280620409, shape=(), dtype=float64)
Updated weight for output layer : tf.Tensor([0.81092077 0.31426378], shape=(2,), dtype=float64)
updated weights for hidden layer: tf.Tensor(
[[0.33178183 1.11653427]
 [0.48623264 1.10747537]], shape=(2, 2), dtype=float64)
Error at the output layer is: tf.Tensor(-0.2180454029901464, shape=(), dtype=float64)
Updated weight for output layer : tf.Tensor([0.90992223 0.42319483], shape=(2,), dtype=float64)
updated weights for hidden layer: tf.Tensor(
[[0.45082444 1.34469928]
 [0.54159805 1.21359241]], shape=(2, 2), dtype=float64)
Error at the output layer is: tf.Tensor(-0.1426341531040205, shape=(), dtype=float64)
Updated weight for output layer : tf.Tensor([0.97734592 0.49449062], shape=(2,), dtype=float64)
updated

#### Convert the updated weight in matrix form

In [4]:
i1=float(input("Enter the first input:"))           # enter neurons as float
i2=float(input("Enter the second input: "))
actual=float(input("Enter the actual output: "))    # Enter the Actual output
rate=float(input("Enter the learning rate: "))      # Enter the Learning Rate

I=[i1,i2]                                     # make it into list
i=np.array(I)                                 #convert it into array
print(i)


l1=[rn.random() for x in range(4)]          # generate 4 random numbers for weights w1,w2,w3,w4
w1=np.array(l1)                             # converts weight into an array
w=w1.reshape(2,2)                           # convert it shape into matrix that is 2*2
print(w)


l2=[rn.random() for x in range(2)]          # generate 2 random numbers for weight for output layer
w2=np.array(l2)                             # convert it into array
print(w2)

threshold=0.01
delta=1

while abs(delta) > threshold:
    h=np.dot(i, w)                               # take dot product of the input and weights to find the hidden layers value
    ah=tf.keras.activations.tanh(h).numpy()      # Apply the activation function
    
    
    out=np.dot(w2,ah)
    o=tf.keras.activations.tanh(out).numpy()
    
    
    delta=o-actual                                           # Error Prediction value
    print("Error at the output layer is:", delta)
    
    
    # Back-Propagation Algorithm
    W2=w2-(rate*delta*ah)                                  
    print("Updated weight for output layer :", W2)
    w2=np.array(W2)
    w2=w2.reshape(1,2)
    
    temp=rate*delta*(w2.T*i)
    W1=w-temp
    print("updated weights for hidden layer:", W1)
    
    # Update weights for next iteration
    w2 = W2
    w = W1
    
    
print("Training complete.")
print("Final weights for hidden layer:", w)
print("Final weights for output layer:", w2)

Enter the first input:1.2
Enter the second input: 2.2
Enter the actual output: 1
Enter the learning rate: 0.5
[1.2 2.2]
[[0.96960426 0.52657955]
 [0.79023942 0.90720846]]
[0.03921725 0.3421744 ]
Error at the output layer is: -0.6393760002343031
Updated weight for output layer : [0.35698323 0.65854301]
updated weights for hidden layer: [[1.10655216 0.77765071]
 [1.04287338 1.37037072]]
Error at the output layer is: -0.23237221434472166
Updated weight for output layer : [0.47300349 0.77464265]
updated weights for hidden layer: [[1.17249989 0.89855487]
 [1.15087664 1.56837669]]
Error at the output layer is: -0.15252953918390155
Updated weight for output layer : [0.54921047 0.85088965]
updated weights for hidden layer: [[1.22276238 0.99070277]
 [1.22874812 1.71114108]]
Error at the output layer is: -0.1147016676573902
Updated weight for output layer : [0.60653395 0.90823477]
updated weights for hidden layer: [[1.26450465 1.06723027]
 [1.29125375 1.82573473]]
Error at the output layer is: -

#### Without While Loop, only for one time back propagation

In [5]:
i1=float(input("Enter the first input:"))    # enter neurons as float
i2=float(input("Enter the second input: "))
actual=float(input("Enter the actual output: "))    # Enter the Actual output
rate=float(input("Enter the learning rate: "))      # Enter the Learning Rate

I=[i1,i2]          # make it into list
i=np.array(I)      #convert it into array
print(i)
print(i.shape)


l1 = [rn.random() for x in range(4)]          # generate 4 random numbers for weights w1,w2,w3,w4
w1=np.array(l1)     # converts weight into an array
w=w1.reshape(2,2)           # convert it shape into matrix that is 2*2
print(w.shape) 

h=np.dot(i,w)      #take dot product of the input and weights to find the hidden layers value
print('Hidden layer values before activation function:', h)
ah=tf.keras.activations.tanh(h)    #Apply the activation function, h is basically a vector or an array, so here it is vectorised operation                                                                   
print('Hidden layer values after activation function:',ah)    #print hidden layer values after applying the activation functions
print(ah.shape)


l2=[rn.random() for x in range(2)]       # generate 2 random numbers for weight for output layer
w2=np.array(l2)                    # convert it into array
print(w2.shape)
out=np.dot(w2,ah)
print("output before the activation function:",out)           # print output before activation function
o=tf.keras.activations.tanh(out)
print("output after the activation function:",o)                # print output after activation function
print(o.shape)

delta=o-actual                                                 # Error Prediction value
print("Error at thr output layer is:", delta)


# Back-Propagation Algorithm
W2=w2-(rate)*(delta)*ah                                  
print("Updated weight  :", W2)
print(W2.shape)

w2=w2.reshape(1,2)
temp=rate*delta*(w2.T*i)
print(temp)

W1=w-temp
print(W1)

Enter the first input:1.1
Enter the second input: 1.3
Enter the actual output: 0.8
Enter the learning rate: 0.7
[1.1 1.3]
(2,)
(2, 2)
Hidden layer values before activation function: [1.10700889 2.01937424]
Hidden layer values after activation function: tf.Tensor([0.80300254 0.96537112], shape=(2,), dtype=float64)
(2,)
(2,)
output before the activation function: 1.533544641470546
output after the activation function: tf.Tensor(0.9110292242176771, shape=(), dtype=float64)
()
Error at thr output layer is: tf.Tensor(0.11102922421767702, shape=(), dtype=float64)
Updated weight  : tf.Tensor([0.84260584 0.76072706], shape=(2,), dtype=float64)
(2,)
tf.Tensor(
[[0.07737205 0.09143969]
 [0.07145088 0.08444195]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[0.24504279 0.87315862]
 [0.50728187 0.65272427]], shape=(2, 2), dtype=float64)
