In [21]:
import pandas as pd
import numpy as np

df=pd.read_excel("C:/Users/sharm/Downloads/linear.xlsx")

In [22]:
df

x1  x2  x3  y
0    2  -4  -6  1
1    1   1   3 -1
2   -2  -1  -3 -1
3    9   1  11  1
4   -1  -1  -1 -1
5    8   0   8  1
6   -3   2   1 -1
7    2   3   8 -1
8    0  -2  -4 -1
9    9  -1   7  1
10  -4   1  -2 -1
11  10   0  10  1
12   8   3  14  1
13   6   2  10  1
14  -1   4   7 -1
15   5  -6  -7  1
16  -3  -2  -7 -1
17   9  -3   3  1
18  -4  -1  -6 -1
19   3   1   5  1
20   2  -4  -6  1
21   1   1   3 -1
22  -2  -1  -3 -1
23   9   1  11  1
24  -1  -1  -1 -1
25   8   0   8  1
26   8  -5  -2  1
27   5   4  13 -1

In [24]:
w1 = int(input("Enter the weight w1: "))
w2 = int(input("Enter the weight w2: "))
w3=int(input("Enter the weight w3: "))
bias = float(input("Enter the initial bias: "))
eta = float(input("Enter the learning rate (eta): "))
w = np.array([bias, w1, w2, w3])

i=1
df1 = pd.DataFrame(columns=['bias', 'w1', 'w2', 'w3'])

for x in range(0,27):
    row=[1]
    for y in range(0,3):
        row.append(df.iloc[x,y])
    output=np.dot(w,row)
    if output >= 0:
        y1=1
    else:
        y1=-1
    
    d=df.iloc[x,3]
    w=w+eta*(d-y1)*x
    print(w)
    df1.loc[i]=w
    i=i+1

    
output_filename = "updated_weights.xlsx"
df1.to_excel(output_filename, index=False)
print("Dataframe is written to Excel file successfully")

Enter the weight w1: 1
Enter the weight w2: 1
Enter the weight w3: 1
Enter the initial bias: 2
Enter the learning rate (eta): 0.5
[2. 1. 1. 1.]
[1. 0. 0. 0.]
[-1. -2. -2. -2.]
[2. 1. 1. 1.]
[2. 1. 1. 1.]
[2. 1. 1. 1.]
[-4. -5. -5. -5.]
[-4. -5. -5. -5.]
[-12. -13. -13. -13.]
[-3. -4. -4. -4.]
[-13. -14. -14. -14.]
[-2. -3. -3. -3.]
[10.  9.  9.  9.]
[10.  9.  9.  9.]
[-4. -5. -5. -5.]
[-4. -5. -5. -5.]
[-20. -21. -21. -21.]
[-3. -4. -4. -4.]
[-21. -22. -22. -22.]
[-2. -3. -3. -3.]
[-2. -3. -3. -3.]
[-2. -3. -3. -3.]
[-24. -25. -25. -25.]
[-1. -2. -2. -2.]
[-25. -26. -26. -26.]
[ 0. -1. -1. -1.]
[26. 25. 25. 25.]
Dataframe is written to Excel file successfully
